# Generated by Django 3.0.3 on 2020-05-07 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_serie_shirt_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='shirt_size',
        ),
        migrations.AddField(
            model_name='serie',
            name='medal',
            field=models.CharField(blank=True, choices=[('GOLD', 'Gold'), ('SILVER', 'Silver'), ('BRONZE', 'Bronze')], max_length=10),
        ),
    ]
