# Generated by Django 3.0.3 on 2020-05-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0006_auto_20200507_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serie',
            name='medal',
        ),
        migrations.AddField(
            model_name='serie',
            name='Style',
            field=models.CharField(blank=True, choices=[('Боевик', 'Боевик'), ('Комедия', 'Комедия'), ('Триллер', 'Триллер'), ('Драма', 'Драма'), ('Зарубежный', 'Зарубежный')], max_length=10, verbose_name='Жанр'),
        ),
    ]
