# Generated by Django 3.0.3 on 2020-04-25 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='film_text',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='film',
            name='film_title',
        ),
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название статьи'),
        ),
    ]
